version: 2

updates:
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    groups:
      build:
        patterns:
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-plugin-module-resolver'
          - 'babel-loader'
          - 'babel-plugin-transform-import-meta'
          - 'webpack'
          - 'webpack-*'

      lint:
        patterns:
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'

      tools:
        patterns:
          - 'husky'
          - 'nodemon'
          - 'npm-run-all'
          - 'lodash'
          - 'source-map-loader'
          - 'sass-*'
          - 'postcss-*'

    ignore:
      - dependency-name: 'eslint-*'
      - dependency-name: 'eslint'

    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      - dependency-type: direct

  - package-ecosystem: github-actions
    directory: /

    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
