services:
  localstack:
    image: localstack/localstack:3.0.2
    ports:
      - "${LOCALSTACK_PORT:-4571}:4566"
    env_file:
      - "compose/aws.env"
    environment:
      DEBUG: ${DEBUG:-1}
      LS_LOG: WARN # Localstack DEBUG Level
      SERVICES: s3,sqs,sns,firehose
      LOCALSTACK_HOST: 127.0.0.1
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - ./compose/start-localstack.sh:/etc/localstack/init/ready.d/start-localstack.sh
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      start_period: 5s
      retries: 3
    networks:
      - cdp-tenant

  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "${REDIS_PORT:-6381}:6379"
    restart: always
    networks:
      - cdp-tenant

  fg-cw-frontend:
    build: ./
    ports:
      - "${FRONTEND_PORT:-8080}:8080"
    links:
      - "localstack:localstack"
      - "redis:redis"
    depends_on:
      localstack:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ".env"
    environment:
      PORT: 8080
      NODE_ENV: development
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    external: true
    name: cdp-tenant
