services:
  fg-cw-frontend:
    build: ./
    ports:
      - "3000:3000"
    env_file:
      - "compose/aws.env"
    environment:
      PORT: 3000
      NODE_ENV: development
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
