include:
  - path: ./compose/compose.cw-frontend.yml
    project_directory: .

services:
  redis:
    image: redis:7.2.3-alpine3.18
    ports:
      - "6379:6379"
    restart: always
    networks:
      - cdp-tenant

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
